enum Errors {
	USUARIO_SEM_PERMISSAO,
	OBJETO_NAO_ENCONTRADO,
	USUARIO_NAO_LOGADO,
	USUARIO_NAO_ENCONTRADO,
	ESTADO_INVALIDO,
	CAMPO_OBRIGATORIO,
	PROF_COM_MANDATO,
	DATA_INVALIDA,
	DADO_INVALIDO,
	PARENTE_NAO_ENCONTRADO,
	ERRO_INTERNO,
}

export default Errors;

